### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by johnfercher** [F-Amaral/go-async#5]
Go-Async have to provide a better understanding of which cause made an async process fail. Today the response of `pool.Process()` only have a `HasError` attribute, if should provide a list of reasons/errors.  

We have to have this feature due this issue: https://github.com/johnfercher/maroto/issues/360

**Comment by zephyrtronium** [comment]
async.ProcessResult also has a GetErrors method which returns each non-nil error that a worker produced.
